// GamingBlogAngularWebClient/src/app/modules/dialogs/login-dialog/login-dialog.component.ts
import { Component, OnInit } from '@angular/core';
import {MatDialogRef} from "@angular/material/dialog";
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {IAuthenticationService} from "../../../core/services/interface-authentication.service";
import {LoginRequest} from "../../../core/models/login-request";
import {LoginResponse} from "../../../core/models/login-response";
import {IApplicationService} from "../../../core/services/interfaces/application.service";
import {HttpErrorResponse} from "@angular/common/http";
import Swal from 'sweetalert2';

@Component({
  selector: 'app-login-dialog',
  templateUrl: './login-dialog.component.html',
  styleUrls: ['./login-dialog.component.scss']
})
export class LoginDialogComponent implements OnInit {

  public loginForm: FormGroup | undefined;

  constructor(private dialogRef: MatDialogRef<LoginDialogComponent>,
              private authenticationService: IAuthenticationService,
              private applicationService: IApplicationService) { }

  ngOnInit(): void {
    this.loginForm = new FormGroup({
      username: new FormControl('', [Validators.required, Validators.minLength(1)]),
      password: new FormControl('', [Validators.required, Validators.minLength(4)])
    });
  }

  public async login(): Promise<void> {
    const loginRequest: LoginRequest = {
      username: this.username.value,
      password: this.password.value
    };

    try {
      let loginResponse: LoginResponse = await this.authenticationService.login(loginRequest);
      this.applicationService.login(loginResponse);
      await Swal.fire({
        titleText: 'Přihlášení proběhlo úspěšně.',
        icon: 'success',
        confirmButtonText: 'Zavřít'
      });
      this.dialogRef.close();
    } catch (err) {
      if (err instanceof HttpErrorResponse) {
        if (err.status === 404) {
          await Swal.fire({
            titleText: 'Uživatel \'' + loginRequest.username + '\' neexistuje.',
            icon: 'error',
            confirmButtonText: 'Zavřít'
          });
        } else if (err.status === 400) {
          await Swal.fire({
            titleText: 'Uživatelské údaje jsou nesprávné.',
            icon: 'error',
            confirmButtonText: 'Zavřít'
          });
        }
      }
    }
  }

  get username(): FormControl {
    return <FormControl>this.loginForm?.get('username');
  }

  get password(): FormControl {
    return <FormControl>this.loginForm?.get('password');
  }
}

<h1 mat-dialog-title>Přihlášení</h1>
<div mat-dialog-content *ngIf="loginForm != undefined" [formGroup]="loginForm">
  <div class="row justify-content-center">
    <mat-form-field appearance="outline">
      <mat-label>Přihlašovací jméno</mat-label>
      <input [value]="username.value" formControlName="username" matInput required placeholder="Zadejte své přihlašovací jméno">
      <mat-error *ngIf="username.hasError('minlength')">
        Přihlašovací jméno nemůže být prázdné.
      </mat-error>
    </mat-form-field>
  </div>

  <div class="row justify-content-center">
    <mat-form-field appearance="outline">
      <mat-label>Heslo</mat-label>
      <input [value]="password.value" formControlName="password" matInput required placeholder="Zadejte své heslo">
      <mat-error *ngIf="password.hasError('minlength')">
        Heslo musí mít nejméně 4 znaky.
      </mat-error>
    </mat-form-field>
  </div>
</div>

<div mat-dialog-actions>
  <button class="btn btn-primary" mat-button (click)="login()">Přihlásit</button>
  <button class="btn btn-danger" mat-button mat-dialog-close="lol">Zrušit</button>
</div>

// gaming-blog-react-web-client/src/Components/Dialogs/LoginDialog.tsx
import React, {FC, useState} from "react";
import {Button, Container, Dialog, DialogTitle, TextField} from "@mui/material";
import {PostService} from "../../services/PostService";
import {AuthenticationService} from "../../services/AuthenticationService";
import {LoginRequest} from "../../Models/Requests/LoginRequest";
import Swal from 'sweetalert2';
import {bindActionCreators} from "redux";
import { actionCreators } from "../../state";
import {useDispatch} from "react-redux";

export interface LoginDialogProps {
    open: boolean;
    onClose: () => void;
}

export interface ValidationError {
    name: string;
    errorText: string;
};

export const LoginDialog: FC<LoginDialogProps> = (props) => {
    const [validationErrors, setValidationErrors] = useState<ValidationError[]>([]);

    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');

    const authenticationService = new AuthenticationService();

    const dispatch = useDispatch();
    const { login } = bindActionCreators(actionCreators, dispatch);

    const validatePassword = (currentValidationErrors: ValidationError[]) => {
        if (password === '') {
            currentValidationErrors.push({
                name: 'password',
                errorText: 'Uživatelské heslo nemůže být prázdné.'
            });
        } else if (password.length < 4) {
            currentValidationErrors.push({
                name: 'password',
                errorText: 'Uživatelské heslo musí mít délku alespoň 4 znaky dlouhou.'
            });
        }
    };

    const validateUsername = (currentValidationErrors: ValidationError[]) => {
        if (username === '') {
            currentValidationErrors.push({
                name: 'username',
                errorText: 'Uživatelské jméno nemůže být prázdné.'
            });
        }
    };

    const onLogin = async () => {
        let currentValidationErrors: ValidationError[] = [];

        validateUsername(currentValidationErrors);
        validatePassword(currentValidationErrors);

        setValidationErrors(currentValidationErrors);

        if (currentValidationErrors.length > 0) {
            return;
        }

        const loginRequest: LoginRequest = {
            username: username,
            password: password
        };

        try {
            let loginResponse = await authenticationService.login(loginRequest);

            await Swal.fire({
                titleText: 'Přihlášení proběhlo úspěšně.',
                icon: 'success',
                confirmButtonText: 'Zavřít'
            });

            login(loginResponse.data);

            props.onClose();
        } catch (err: any) {
            if (err.response) {
                if (err.response.status === 400 || err.response.status === 404) {
                    await Swal.fire({
                        titleText: 'Uživatelské údaje jsou nesprávné.',
                        icon: 'error',
                        confirmButtonText: 'Zavřít'
                    });
                }
            }
        }
    }

    return (
        <Dialog onClose={props.onClose} open={props.open}>
            <Container>
                <DialogTitle>Přihlašovací dialogové okno</DialogTitle>

                <div className="row mb-3">
                    <TextField required id="outlined-required"
                               value={username}
                               onChange={(event) => setUsername(event.target.value)}
                               error={validationErrors.find(x => x.name === 'username') !== undefined}
                               helperText={validationErrors.find(x => x.name === 'username') !== undefined ? validationErrors.find(x => x.name === 'username')?.errorText : ''}
                               label="Uživatelské jméno"
                               variant="outlined"/>
                </div>

                <div className="row mb-5">
                    <TextField required id="outlined-required"
                               value={password}
                               onChange={(event) => setPassword(event.target.value)}
                               error={validationErrors.find(x => x.name === 'password') !== undefined}
                               helperText={validationErrors.find(x => x.name === 'password') !== undefined ? validationErrors.find(x => x.name === 'password')?.errorText : ''}
                               label="Uživatelské heslo"
                               type="password"
                               variant="outlined"/>
                </div>

                <div className="row mb-2">
                    <Button variant="contained" onClick={onLogin}>
                        Přihlásit se
                    </Button>
                </div>
            </Container>
        </Dialog>
    );
}
